version: '3.8'

services:
  # app:
  #   image: todo-front-dev
  #   build:
  #     context: ./todo-frontend
  #     dockerfile: dev.Dockerfile
  #   container_name: todo-front-dev
  
  server:
    image: stulab-server-dev
    ports:
      - 3000:3000
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: stulab-server-dev
    volumes:
      - ./backend/.:/opt/stulab-server/.
    # environment:
    #   - REDIS_URL=//redis_dev:6379
    # depends_on:
    #   - redis

  nginx:
    image: nginx:1.20.1
    build:
      context: ./proxy
      dockerfile: Dockerfile
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      # - app
      - server

  # redis:
  #   image: redis
  #   container_name: redis_dev
  #   command: ['redis-server', '--appendonly', 'yes']
  #   volumes:
  #     - redis_data:/data

# volumes:
#   redis_data: